# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  gen_test:
    cmds:
      - rm -rvf testdata/
      - mkdir -p testdata/{1,2,3,4}
      - touch ./testdata/{1,2,3,4}/{1,2,3,4,5}.{mkv,mp4,ass,ttf}
      - mkdir ./garage-ui/dist
      - touch ./garage-ui/dist/index.html
      - ls -al ./testdata
  clean:
    cmds:
      - go clean --cache
      - rm -rvf build
      - rm -rvf dist
      - rm -rvf testdata/
      - rm -rvf javbus/
  build:
    cmds:
      - go build -o build/garage ./src
  di:
    cmds:
      - wire ./garage_di
  protoc:
    cmds:
      - protoc --go_out=./garage_server --go_opt=paths=source_relative --go-grpc_out=./garage_server --go-grpc_opt=paths=source_relative proto/task.proto
      # - protoc --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:./garage-ui/src/api ./proto/task.proto