// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gsxhnd/garage/garage_server/db"
	"github.com/gsxhnd/garage/garage_server/handler"
	"github.com/gsxhnd/garage/garage_server/middleware"
	"github.com/gsxhnd/garage/garage_server/router"
	"github.com/gsxhnd/garage/garage_server/service"
	"github.com/gsxhnd/garage/utils"
)

// Injectors from wire.go:

func InitApp() (*Application, error) {
	config, err := utils.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := utils.NewLogger()
	middlewarer := middleware.NewMiddleware(logger)
	database, err := db.NewDatabase(config, logger)
	if err != nil {
		return nil, err
	}
	pingService := service.NewPingService(logger, database)
	pingHandler := handler.NewPingHandler(pingService)
	handlerHandler := handler.Handler{
		PingHandler: pingHandler,
	}
	routerRouter, err := router.NewRouter(config, middlewarer, handlerHandler)
	if err != nil {
		return nil, err
	}
	application := NewApplication(routerRouter)
	return application, nil
}
