// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/gin-gonic/gin"
	"github.com/gsxhnd/garage/garage_server/handler"
	"github.com/gsxhnd/garage/garage_server/middleware"
	"github.com/gsxhnd/garage/garage_server/routes"
	"github.com/gsxhnd/garage/garage_server/service"
	"github.com/gsxhnd/garage/utils"
)

// Injectors from wire.go:

func InitApp() (*Application, error) {
	engine := gin.New()
	config, err := utils.NewConfig()
	if err != nil {
		return nil, err
	}
	logger := utils.NewLogger(config)
	middlewarer := middleware.NewMiddleware(logger)
	testService := service.NewTestService(logger)
	pingHandler := handler.NewPingHandle(logger, testService)
	routesRoutes := &routes.Routes{
		Engine:      engine,
		Middleware:  middlewarer,
		PingHandler: pingHandler,
	}
	application := NewApplication(routesRoutes)
	return application, nil
}
