name: Release Rust

on:
  push:

jobs:
  build:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Add Rust
        uses: dtolnay/rust-toolchain@master
      - run: cargo version
